services:
  postgres:
    extends:
      service: postgres
      file: compose.yaml
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    extends:
      service: redis
      file: compose.yaml

  api:
    extends:
      service: api
      file: compose.yaml
    command: ["./dev.sh"]
    volumes:
      - ./api:/app
    environment:
      DEBUG: "True"

  worker:
    extends:
      service: worker
      file: compose.yaml
    volumes:
      - ./api:/app
    command: sh -c "pip install watchdog && watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery -A config worker -l info"


volumes:
  pgdata:
