services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD:
    x-defang-postgres: true
    ports:
      - mode: host
        target: 5432  
        published: 5432

  redis:
    image: redis:6.2
    x-defang-redis: true
    ports:
      - mode: host
        target: 6379
        published: 6379

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: ./run.sh
    domainname: api.match.connectier.app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres?sslmode=${POSTGRES_SSLMODE}
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      WEAVIATE_ENDPOINT: ${WEAVIATE_ENDPOINT}
      WEAVIATE_API_KEY: ${WEAVIATE_API_KEY}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s

  worker:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: celery -A config worker -l info
    depends_on:
      - postgres
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres?sslmode=${POSTGRES_SSLMODE}
      REDIS_URL: redis://redis:6379/0
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      WEAVIATE_ENDPOINT: ${WEAVIATE_ENDPOINT}
      WEAVIATE_API_KEY: ${WEAVIATE_API_KEY}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      LIGHTPANDA_API_KEY: ${LIGHTPANDA_API_KEY}

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_BASE_URL=https://api.match.connectier.app
    domainname: match.connectier.app
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      NEXT_PUBLIC_API_BASE_URL: https://api.match.connectier.app
