# Generated by Django 4.2.21 on 2025-09-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_workspace_relationships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='source',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
