# Generated by Django 4.2.21 on 2025-09-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_document_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='scrape_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='document',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
