# Generated by Django 4.2.21 on 2025-09-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_document_scrape_status_alter_document_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
