# Generated by Django 4.2.21 on 2025-09-28 09:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_document_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingJobRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='running', max_length=16)),
                ('matching_config_snapshot', models.JSONField(blank=True, default=dict)),
                ('plan_snapshot', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('matching_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.matchingjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchingSearchLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criterion_id', models.CharField(max_length=128)),
                ('criterion_label', models.CharField(blank=True, max_length=255)),
                ('query_text', models.TextField()),
                ('query_type', models.CharField(choices=[('source', 'Source'), ('target', 'Target')], max_length=16)),
                ('limit', models.PositiveIntegerField()),
                ('returned_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='core.matchingjobrun')),
                ('target_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_search_logs', to='core.entity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchingSearchHitLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank', models.PositiveIntegerField(default=1)),
                ('chunk_text', models.TextField(blank=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_hit_logs', to='core.documentchunk')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='core.matchingsearchlog')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='MatchingEvaluationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('average_score', models.FloatField(blank=True, null=True)),
                ('coverage', models.FloatField(blank=True, null=True)),
                ('search_hit_ratio', models.FloatField(blank=True, null=True)),
                ('summary_reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='core.matchingjobrun')),
                ('target_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_logs', to='core.entity')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('run', 'target_entity')},
            },
        ),
        migrations.CreateModel(
            name='MatchingEvaluationDetailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criterion_id', models.CharField(max_length=128)),
                ('criterion_label', models.CharField(blank=True, max_length=255)),
                ('rating_value', models.IntegerField(blank=True, null=True)),
                ('rating_name', models.CharField(blank=True, max_length=32)),
                ('rating_prompt', models.TextField(blank=True)),
                ('rating_response', models.TextField(blank=True)),
                ('reasoning_prompt', models.TextField(blank=True)),
                ('reasoning_response', models.TextField(blank=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.matchingevaluationlog')),
            ],
            options={
                'ordering': ['criterion_id'],
            },
        ),
    ]
