# Generated by Django 4.2.21 on 2025-09-28 11:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_matching_audit_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingJobUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('matching_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='core.matchingjob')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='core.matchingjobrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
